[package]
name = "xtask"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true

[package.metadata.dist]
dist = false

[package.metadata.cargo-machete]
ignored = []
